"""Phase 17 Workstream B -- evaluator independence.

Track A answers are already generated by ONE model (`llama2`, Phase 14's frozen agent
model) and judged for detection by a DIFFERENT model family/checkpoint (`qwen2.5:7b`,
every Phase 17 judge/detector) -- so the Phase 17 security numbers already avoid the
generator == judge correlation the workstream warns about. This module adds the
explicit, MEASURED comparison the workstream asks for: a SECOND correctness judge using
the SAME model that generated the answers (`llama2`), run over the identical 150 Track A
answers `utility_repeats.py` already collected (run 0), so self-judging vs
independent-judging can be compared directly on one fixed set of real outputs -- no new
generation, only a second judge pass.

Reports: judge agreement/disagreement rate, per-category breakdown (both-correct,
both-incorrect, judge-disagree), and whether the qualitative conclusion ("does B0 succeed
on most of the 150 real LoCoMo cases") would change under either judge.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

from phase3.evaluation.agent.llm_judge_correctness import _build_judge_messages, _parse_verdict
from phase3.evaluation.llm.provider import GenerationConfig
from phase17.stats import paired_delta, rate_with_ci

DATA = Path(__file__).parent / "data"
IN = DATA / "utility_repeats.json"
OUT = DATA / "evaluator_independence.json"


def run() -> dict:
    from phase12.propagation.ollama_provider import OllamaProvider
    from phase14.campaign import TRACK_A_LOCOMO_PER_TASK_CAP
    from phase14.track_a_benign import build_track_a_cases

    cases = {c.task_id: c for c in build_track_a_cases(150, per_task_cap=TRACK_A_LOCOMO_PER_TASK_CAP)}
    run0 = json.loads(IN.read_text(encoding="utf-8"))["runs"][0]
    self_judge = OllamaProvider(model="llama2")  # SAME model as the answer generator (Phase 14's agent model)
    cfg = GenerationConfig(temperature=0.0, seed=42, max_tokens=8, enable_thinking=False, n_ctx=4096)

    rows: List[dict] = []
    for x in run0:
        c = cases[x["id"]]
        v_self = _parse_verdict(self_judge.generate(_build_judge_messages(c.question, c.gold_answer, x["answer"] or ""), cfg).text)
        rows.append({"id": x["id"], "answer": x["answer"], "independent_judge(qwen)": bool(x["llm_judge"]),
                     "self_judge(llama2)": bool(v_self) if v_self is not None else False, "self_judge_undefined": v_self is None})

    indep = [r["independent_judge(qwen)"] for r in rows]
    slf = [r["self_judge(llama2)"] for r in rows]
    agree = sum(a == b for a, b in zip(indep, slf))
    result = {
        "n": len(rows), "independent_judge_model": "qwen2.5:7b", "self_judge_model": "llama2 (same as answer generator)",
        "independent_judge_rate": rate_with_ci(sum(indep), len(rows)), "self_judge_rate": rate_with_ci(sum(slf), len(rows)),
        "agreement_rate": rate_with_ci(agree, len(rows)), "paired": paired_delta(indep, slf),
        "n_self_judge_undefined": sum(r["self_judge_undefined"] for r in rows),
        "qualitative_conclusion_changes": abs(sum(indep) - sum(slf)) / len(rows) > 0.10,  # >10pt swing would flip a headline claim
        "disagreement_examples": [r for r in rows if r["independent_judge(qwen)"] != r["self_judge(llama2)"]][:10],
    }
    OUT.write_text(json.dumps(result, indent=2), encoding="utf-8")
    return result


if __name__ == "__main__":
    r = run()
    print("independent", r["independent_judge_rate"], "self", r["self_judge_rate"], "agreement", r["agreement_rate"],
          "conclusion_changes", r["qualitative_conclusion_changes"])
    print("DONE")
